name: Release workflow

on:
  release:
    types:
      - published

jobs:
  docker-image:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Login to docker registry
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}
      - name: Run buildx
        run: |
          docker buildx build \
            --tag faucet/test-host:${{ github.event.release.tag_name }} \
            --tag faucet/test-host:latest \
            --platform linux/386,linux/amd64 \
            --output "type=registry" \
            --file Dockerfile \
            .
